config/routes.rb
Rails.application.routes.draw do
  
  resources :pins

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "pins#index"
  get "about" => "pages#about"

  
 
end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  	 validates :image, presence: true
  	 validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :pins

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
   devise_parameter_sanitizer.for(:sign_up) << :subscription_type
   devise_parameter_sanitizer.for(:account_update) << :subscription_type
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order('created_at DESC').paginate(page: params[:page], per_page: 12)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pin
    @pin = Pin.find(params[:id])
  end

  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: 'Not authorized to edit this pin' if @pin.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pin_params
    params.require(:pin).permit(:description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-static-top.navbar-default{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Pinster", root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to root_path do
            %i.fa.fa-home  Home
        %li
          = link_to about_path do
            %i.fa.fa-pencil  About
        - if user_signed_in?
          %li
            = link_to new_pin_path do
              %i.fa.fa-plus  New Pin
          %li
            = link_to edit_user_registration_path do
              %i.fa.fa-cog  Account Settings
          %li
            = link_to destroy_user_session_path, method: :delete do
              %i.fa.fa-sign-out  Logout
        - else
          - if current_page?(:controller => 'devise/sessions', :action => 'new')
            %li
              = link_to new_user_registration_path do
                %i.fa.fa-sign-in  Sign up
          - else
            %li
              = link_to new_user_session_path do
                %i.fa.fa-sign-in  Sign in
    / /.navbar-collapse
  / /.container

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pinster
    = favicon_link_tag image_path('favicon.png')
    = favicon_link_tag image_path('favicon.png'), rel: 'apple-touch-icon', type: 'image/png'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
  %body
    = render 'layouts/header'
    .container
      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert alert-info")
      = yield

app/views/pages/_home.html.haml
.jumbotron.center
  %h1
    Welcome to
    %span{style: "color: #c0392b"} Pinster
  %p
    %a.btn.btn-primary.btn-lg{href: "/users/sign_in"}
      %i.fa.fa-user  Login
    = link_to "Sign up", new_user_registration_path, class:"btn btn-default btn-lg"

app/views/pages/about.html.haml
.container-fluid
  .jumbotron.center
    %h2{style: "position:relative; top: -35px; font-family:'Droid Serif', serif;"} About me
    / Button trigger modal
    = image_tag("manmeet_pic.jpg", :alt => "Manmeet", class:"center", style:"max-width:50%; max-height:50%; position:relative; top:-5px;")
    %h3.center{style: "font-family:'Lobster', cursive; font-size: 4.0vh;"} Manmeet Singh Saluja
    %a.zocial.icon.facebook{href: "https://www.facebook.com/connectwithmanmeet", target: "_blank"}
    %a.zocial.icon.twitter{href: "https://twitter.com/iamsaluja", target: "_blank"}
    %a.zocial.icon.linkedin{href: "http://www.linkedin.com/pub/manmeet-singh/36/243/347", target: "_blank"}
/ ./jumbotron
/ /.container-fluid

app/views/pages/home.html.erb
<div class="jumbotron center">
<h1>Welcome to <span style="color: #c0392b">Pinteresting</span></h1>
<% if user_signed_in? %>
	# do something
<% else %>
<p>
	<a href="/users/sign_in" class="btn btn-primary btn-lg"><i class="fa fa-user">&nbsp;Login</i></a>
	<%= link_to "Sign up", new_user_registration_path, class:"btn btn-default btn-lg" %>
</p>
<% end %>
</div>

app/views/pins/_form.html.haml
= form_for @pin, html: { multipart: true } do |f|
  - if @pin.errors.any?
    #error_explanation
      %h2
        = pluralize(@pin.errors.count, "error")
        prohibited this pin from being saved:
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :image
    = f.file_field :image, class: "form-control"
  .form-group
    = f.label :description
    = f.text_field :description, class: "form-control"
  .form-group
    = f.submit class: "btn btn-primary"

app/views/pins/edit.html.haml
%h1 Editing pin
= render 'form'
= link_to 'Show', @pin
|
\#{link_to 'Back', pins_path}

app/views/pins/index.html.haml
= render 'pages/home' unless user_signed_in?
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      = link_to image_tag(pin.image.url(:medium)), pin
      .panel-body
        %p= pin.description
        %p
          %strong= pin.user.name if pin.user
          - if pin.user
            - unless pin.user.subscription_type == ""
              %i{style: "font-size: 12px;"}
                (#{pin.user.subscription_type})
        - if current_user && pin.user == current_user
          .actions
            = link_to edit_pin_path(pin) do
              %span.glyphicon.glyphicon-edit
              Edit
            = link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do
              %span.glyphicon.glyphicon-trash
              Delete
.center
  = will_paginate @posts, renderer: BootstrapPagination::Rails

app/views/pins/new.html.haml
%h1 New pin
= render 'form'
= link_to 'Back', pins_path

app/views/pins/show.html.haml
= link_to 'Back', pins_path
.row
  .col-md-offset-2.col-md-8
    .panel.panel-default
      .panel-heading.center
        = image_tag @pin.image.url(:medium)
      .panel-body
        %p= @pin.description
        %p
          %strong= @pin.user.name if @pin.user
        - if @pin.user == current_user
          = link_to edit_pin_path(@pin) do
            %span.glyphicon.glyphicon-edit
            Edit
          = link_to @pin, method: :delete, data: { confirm: 'Are you sure?' } do
            %span.glyphicon.glyphicon-trash
            Delete